# Generated by Django 3.1.3 on 2021-06-27 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_num', models.IntegerField(default=1)),
                ('fullName', models.CharField(default='FirstName LastName', max_length=50)),
                ('gender', models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('location', models.CharField(blank=True, default='Pune,India', max_length=30)),
                ('pro_pic', models.ImageField(null=True, upload_to='')),
                ('bio', models.TextField(blank=True, default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum deserunt cum consectetur ratione quisquam accusamus ipsum, voluptates repellendus obcaecati? Minima?', max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
