# Generated by Django 3.1.3 on 2021-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
