# Generated by Django 3.1.3 on 2021-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_pro_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dp_num',
            new_name='profilePicture_num',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum deserunt cum consectetur ratione quisquam accusamus ipsum, voluptates repellendus obcaecati? Minima?', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Pune,India', max_length=30),
        ),
    ]
