# Generated by Django 3.1.3 on 2021-06-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210627_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthDate',
            field=models.CharField(default='3 July 2021', help_text='Enter Date in 1 January 2000 format.', max_length=50),
        ),
    ]
