# Generated by Django 3.1.3 on 2021-06-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210627_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_Followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_Following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_Posts',
            field=models.IntegerField(default=0),
        ),
    ]
