# Generated by Django 3.1.3 on 2021-07-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210705_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_of_comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos/'),
        ),
    ]
