# Generated by Django 3.1.3 on 2021-07-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210705_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='India', max_length=30),
        ),
    ]
