# Generated by Django 3.1.3 on 2021-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210706_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
